name: Full Stack CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore ./Backend/EmployeeManagement.API

    - name: Build Backend
      run: dotnet build ./Backend/EmployeeManagement.API --no-restore

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        cd Frontend/employee-ui
        npm install

    - name: Build Angular App
      run: |
        cd Frontend/employee-ui
        npm run build
